[package]
name = "tree-sitter-l00pr2"
description = "Language for sequencing data (mostly notes) and generating audio"
version = "0.1.0"
authors = ["Magyari Krisztián <magyarikrisztianbusiness@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "l00pr2"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "github.com/mkkrisz/l00pr"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.8"
